site_name: Guy Weibel - Data Science Portfolio
site_url: https://Guy1Weibel.github.io/

site_author: Guy Weibel
site_description: A portfolio showcasing my data science projects.

repo_url: https://github.com/Guy1Weibel/guyweibel.github.io
repo_name: Guy1Weibel/guyweibel.github.io # Use the full repo name for 

# Theme Configuration
theme:
  name: material
  font:
    text: Georgia, serif
    code: Roboto Mono
  palette:
    - scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/brightness-7 # Icon to switch TO light mode
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-4 # Icon to switch TO dark mode
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy
    - content.code.annotate

extra_css:
  - https://unpkg.com/aos@2.3.1/dist/aos.css
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/aos@2.3.1/dist/aos.js
  - js/extra.js

# Extensions for Markdown features
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
  - attr_list

# Navigation Structure
nav:
  - Home: index.md
  - About Me: about.md
  - Projects:
      - Overview: projects/index.md
      - Project Alpha: projects/project_alpha.md
      - Project Beta: projects/project_beta.md
      # Add more projects here as projects/your_project_name.md
  - Resume: resume.md
  - Contact: contact.md
