site_name: Guy Weibel - Data Science Portfolio
site_url: https://guy1weibel.github.io/

site_author: Guy Weibel
site_description: A portfolio showcasing my data science projects.

repo_url: https://github.com/Guy1Weibel/guyweibel.github.io
repo_name: Guy1Weibel/guyweibel.github.io

# Theme Configuration
theme:
  name: material
  font:
    text: Georgia, serif
    code: Roboto Mono
  palette:
    scheme: slate
    primary: blue grey
    accent: light blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.cards

extra_css:
  - css/extra.css
  - https://unpkg.com/aos@2.3.1/dist/aos.css
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/aos@2.3.1/dist/aos.js
  - js/extra.js

# Extensions for Markdown features
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.emoji: # Ensure emoji extension is explicitly enabled
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Navigation Structure
nav:
  - Home: index.md
  - About Me: about.md
  - Projects: 
      - Overview: projects/index.md 
      - Phage DMS: projects/phage_dms.md
      - STRAP Plastic Recycling: projects/strap_recycling.md # <-- ADDED STRAP
      # - Advanced Churn Prediction Model: projects/churn_prediction_model.md # <-- REMOVED CHURN
      - Project Alpha: projects/project_alpha.md
      - Project Beta: projects/project_beta.md
  - Contact: contact.md
